export { default as Admin } from "./Admin";
export { default as Register } from "./Register";
export { default as Login } from "./Login";
export { default as Home } from "./Home";
export { default as About } from "./About.tsx";
export { default as Statistics } from "./Statistics.tsx";
export { default as Main } from "./Main";
export { default as TTT } from "./TTT";
export { default as TZFE } from "./TZFE";
